#!/usr/bin/env bash
# =============================================================================
# build.sh — Mars Rover NuSMV build script
# FORMAL METHODS — SE-320  |  BESE-14B  |  Group 01
#
# Usage:
#   ./build.sh              — build mars_rover.smv only
#   ./build.sh --run        — build and run NuSMV on correct model
#   ./build.sh --run --faulty-a  — run faulty model A (from faulty/ subfolder)
#   ./build.sh --run --faulty-b  — run faulty model B (from faulty/ subfolder)
#   ./build.sh --run --int  — interactive mode
# =============================================================================

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUTPUT="$SCRIPT_DIR/mars_rover.smv"

FRAGMENTS=(
  "01_power.smv"
  "02_comm.smv"
  "03_nav.smv"
  "04_main.smv"
  "05_properties.smv"
)

# ── ANSI colour codes ─────────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
MAGENTA='\033[0;35m'
BOLD='\033[1m'
DIM='\033[2m'
RESET='\033[0m'

# ── Build step (always runs) ──────────────────────────────────────────────────
echo "Building $OUTPUT ..."

cat > "$OUTPUT" << 'EOF'
-- Mars Rover Autonomous Navigation Protocol: AUTO-GENERATED
-- DO NOT EDIT THIS FILE DIRECTLY: edit the source fragments and re-run build.sh

EOF

for frag in "${FRAGMENTS[@]}"; do
  frag_path="$SCRIPT_DIR/$frag"
  if [[ ! -f "$frag_path" ]]; then
    echo "ERROR: Fragment not found: $frag_path" >&2
    exit 1
  fi
  echo "  + $frag"
  echo "" >> "$OUTPUT"
  cat "$frag_path" >> "$OUTPUT"
  echo "" >> "$OUTPUT"
done

echo "Done — output: $OUTPUT"
echo ""

# Run NuSMV 
if [[ "$1" == "--run" || "$2" == "--run" ]]; then
  if ! command -v nusmv &>/dev/null && ! command -v NuSMV &>/dev/null; then
    echo "WARNING: nusmv not found on PATH. Skipping verification run."
    exit 0
  fi

  NUSMV_CMD="nusmv"
  command -v nusmv &>/dev/null || NUSMV_CMD="NuSMV"

  # Determine target file and label
  TARGET="$OUTPUT"
  MODEL_LABEL="CORRECT MODEL"

  if [[ "$1" == "--faulty-a" || "$2" == "--faulty-a" ]]; then
    TARGET="$SCRIPT_DIR/faulty/mars_rover_faulty_A.smv"
    MODEL_LABEL="FAULTY MODEL A"
  elif [[ "$1" == "--faulty-b" || "$2" == "--faulty-b" ]]; then
    TARGET="$SCRIPT_DIR/faulty/mars_rover_faulty_B.smv"
    MODEL_LABEL="FAULTY MODEL B"
  fi

  if [[ ! -f "$TARGET" ]]; then
    echo "ERROR: Target not found: $TARGET" >&2
    exit 1
  fi

  # Interactive mode
  if [[ "$1" == "--int" || "$2" == "--int" ]]; then
    echo "Launching NuSMV in interactive mode..."
    "$NUSMV_CMD" -int "$TARGET"
    exit 0
  fi

  # Pretty-print NuSMV output
  echo -e "${BOLD}╔══════════════════════════════════════════════════════════════════╗${RESET}"
  printf "${BOLD}║   NuSMV Verification — Mars Rover   [%-28s]${RESET}\n" "$MODEL_LABEL"
  echo -e "${BOLD}╚══════════════════════════════════════════════════════════════════╝${RESET}"
  echo ""

  RAW_OUTPUT=$("$NUSMV_CMD" "$TARGET" 2>&1)

  prop_num=0
  in_trace=0
  trace_lines=()

  flush_trace() {
    if [[ ${#trace_lines[@]} -gt 0 ]]; then
      echo -e "${DIM}     ┌─ Counterexample Trace ──────────────────────────────────────${RESET}"
      for tl in "${trace_lines[@]}"; do
        if [[ "$tl" =~ "-> State:" ]]; then
          echo -e "${CYAN}     │  $tl${RESET}"
        elif [[ "$tl" =~ "Loop starts here" ]]; then
          echo -e "${MAGENTA}     │  ◄── $tl${RESET}"
        else
          formatted="$tl"
          formatted="${formatted/nav_state = SAFE_MODE/${YELLOW}nav_state = SAFE_MODE${RESET}}"
          formatted="${formatted/nav_state = DRIVING/${RED}nav_state = DRIVING${RESET}}"
          formatted="${formatted/nav_state = AUTONAV/${RED}nav_state = AUTONAV${RESET}}"
          formatted="${formatted/nav_state = OBSTACLE_DETECTED/${MAGENTA}nav_state = OBSTACLE_DETECTED${RESET}}"
          formatted="${formatted/nav_state = REPLANNING/${CYAN}nav_state = REPLANNING${RESET}}"
          formatted="${formatted/nav_state = IDLE/${GREEN}nav_state = IDLE${RESET}}"
          formatted="${formatted/power_state = CRITICAL/${RED}power_state = CRITICAL${RESET}}"
          formatted="${formatted/power_state = LOW/${YELLOW}power_state = LOW${RESET}}"
          formatted="${formatted/power_state = NOMINAL/${GREEN}power_state = NOMINAL${RESET}}"
          formatted="${formatted/comm_state = BLACKOUT/${RED}comm_state = BLACKOUT${RESET}}"
          formatted="${formatted/comm_state = AUTOMODE/${MAGENTA}comm_state = AUTOMODE${RESET}}"
          formatted="${formatted/comm_state = DEGRADED/${YELLOW}comm_state = DEGRADED${RESET}}"
          formatted="${formatted/comm_state = CONNECTED/${GREEN}comm_state = CONNECTED${RESET}}"
          formatted="${formatted/power_fault_active = TRUE/${RED}power_fault_active = TRUE${RESET}}"
          formatted="${formatted/power_fault_active = FALSE/${GREEN}power_fault_active = FALSE${RESET}}"
          formatted="${formatted/fault_latch = TRUE/${RED}fault_latch = TRUE${RESET}}"
          formatted="${formatted/fault_latch = FALSE/${GREEN}fault_latch = FALSE${RESET}}"
          formatted="${formatted/pre_approved_loaded = TRUE/${GREEN}pre_approved_loaded = TRUE${RESET}}"
          formatted="${formatted/pre_approved_loaded = FALSE/${RED}pre_approved_loaded = FALSE${RESET}}"
          echo -e "${DIM}     │${RESET}  $formatted"
        fi
      done
      echo -e "${DIM}     └────────────────────────────────────────────────────────────${RESET}"
      trace_lines=()
      in_trace=0
    fi
  }

  while IFS= read -r line; do
    # Skip NuSMV banner
    if [[ "$line" =~ "This is NuSMV" || "$line" =~ "Enabled addons" ||
          "$line" =~ "For more information" || "$line" =~ "or email to" ||
          "$line" =~ "Please report bugs" || "$line" =~ "Copyright" ||
          "$line" =~ "This version of NuSMV" ]]; then
      continue
    fi

    if [[ "$line" =~ "specification" && "$line" =~ "is true" ]]; then
      flush_trace
      prop_num=$((prop_num + 1))
      logic="CTL"
      [[ "$line" =~ "LTLSPEC" || "$line" =~ " G " || "$line" =~ " G(" ]] && logic="LTL"
      prop_text=$(echo "$line" | sed 's/.*specification[[:space:]]*//' | sed 's/[[:space:]]*is true.*//')
      echo -e "  ${BOLD}[$prop_num]${RESET} ${DIM}($logic)${RESET}  ${GREEN}${BOLD}✔  TRUE${RESET}"
      echo -e "      ${DIM}$prop_text${RESET}"
      echo ""

    elif [[ "$line" =~ "specification" && "$line" =~ "is false" ]]; then
      flush_trace
      prop_num=$((prop_num + 1))
      logic="CTL"
      [[ "$line" =~ "LTLSPEC" || "$line" =~ " G " || "$line" =~ " G(" ]] && logic="LTL"
      prop_text=$(echo "$line" | sed 's/.*specification[[:space:]]*//' | sed 's/[[:space:]]*is false.*//')
      echo -e "  ${BOLD}[$prop_num]${RESET} ${DIM}($logic)${RESET}  ${RED}${BOLD}✘  FALSE${RESET}"
      echo -e "      ${DIM}$prop_text${RESET}"
      echo ""
      in_trace=1

    elif [[ $in_trace -eq 1 ]]; then
      if [[ "$line" =~ "Trace Description:" || "$line" =~ "Trace Type:" ||
            "$line" =~ "as demonstrated" ]]; then
        continue
      fi
      stripped="${line#"${line%%[! ]*}"}"
      [[ -n "$stripped" ]] && trace_lines+=("$stripped")
    fi

  done <<< "$RAW_OUTPUT"

  flush_trace

  # Summary
  total_true=$(echo "$RAW_OUTPUT" | grep -c "is true" || true)
  total_false=$(echo "$RAW_OUTPUT" | grep -c "is false" || true)
  total=$((total_true + total_false))

  echo ""
  echo -e "${BOLD}══════════════════════════════════════════════════════════════════${RESET}"
  echo -e "${BOLD}  Summary: $total properties checked${RESET}"
  echo -e "  ${GREEN}${BOLD}✔ TRUE : $total_true${RESET}"
  echo -e "  ${RED}${BOLD}✘ FALSE: $total_false${RESET}"
  echo -e "${BOLD}══════════════════════════════════════════════════════════════════${RESET}"
  echo ""
fi