#!/usr/bin/env bash
# =============================================================================
# build.sh — Mars Rover NuSMV build script
# FORMAL METHODS — SE-320  |  BESE-14B  |  Group 01
#
# NuSMV does not support #include or multi-file input natively.
# This script concatenates the split source files in the correct order
# into a single runnable mars_rover.smv, then optionally runs NuSMV on it.
#
# Fragment order matters — NuSMV requires MODULE main to appear LAST,
# and all referenced modules to be defined before they are instantiated.
#
# Usage:
#   ./build.sh              — build mars_rover.smv only
#   ./build.sh --run        — build and run NuSMV
#   ./build.sh --run --int  — build and run NuSMV in interactive mode
# =============================================================================

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUTPUT="$SCRIPT_DIR/mars_rover.smv"

# Source fragments in dependency order:
#   1. PowerModule  — no dependencies
#   2. CommModule   — reads power_state from PowerModule
#   3. NavModule    — reads from both Power and Comm
#   4. main         — instantiates all three modules
#   5. properties   — SPEC and LTLSPEC (must come after main)
FRAGMENTS=(
  "01_power.smv"
  "02_comm.smv"
  "03_nav.smv"
  "04_main.smv"
  "05_properties.smv"
)

echo "Building $OUTPUT ..."

# Write header
cat > "$OUTPUT" << 'EOF'
-- =============================================================================
-- FORMAL METHODS — SE-320  |  BESE-14B  |  Group 01
-- Mars Rover Autonomous Navigation Protocol — AUTO-GENERATED
-- Tool: NuSMV 2.6+
-- Generated by: build.sh
-- Source files: 01_power.smv  02_comm.smv  03_nav.smv  04_main.smv  05_properties.smv
-- DO NOT EDIT THIS FILE DIRECTLY — edit the source fragments and re-run build.sh
-- =============================================================================

EOF

# Concatenate each fragment with a separator comment
for frag in "${FRAGMENTS[@]}"; do
  frag_path="$SCRIPT_DIR/$frag"
  if [[ ! -f "$frag_path" ]]; then
    echo "ERROR: Fragment not found: $frag_path" >&2
    exit 1
  fi
  echo "  + $frag"
  echo "" >> "$OUTPUT"
  cat "$frag_path" >> "$OUTPUT"
  echo "" >> "$OUTPUT"
done

echo "Done — output: $OUTPUT"
echo ""

# Optionally run NuSMV
if [[ "$1" == "--run" || "$2" == "--run" ]]; then
  if ! command -v nusmv &>/dev/null && ! command -v NuSMV &>/dev/null; then
    echo "WARNING: nusmv not found on PATH. Skipping verification run."
    echo "Install NuSMV 2.6+ and ensure it is on your PATH, then re-run with --run."
    exit 0
  fi

  NUSMV_CMD="nusmv"
  command -v nusmv &>/dev/null || NUSMV_CMD="NuSMV"

  if [[ "$1" == "--int" || "$2" == "--int" ]]; then
    echo "Launching NuSMV in interactive mode..."
    "$NUSMV_CMD" -int "$OUTPUT"
  else
    echo "Running NuSMV..."
    echo "--------------------------------------------------------------"
    "$NUSMV_CMD" "$OUTPUT"
    echo "--------------------------------------------------------------"
  fi
fi
